name: CI Pipeline

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch all history so Gitleaks can scan it
          fetch-depth: 0

      - name: Run Gitleaks secret scan
        uses: gitleaks/gitleaks-action@v2
        env:
          # This is an optional personal access token to prevent rate limiting
          # when Gitleaks updates its rules.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
