name: semgrep-scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  semgrep:
    name: Semgrep scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      # This is the step that needs to be fixed
      - name: Run Semgrep
        run: |
          semgrep scan --config .semgrep.yml --sarif --output semgrep.sarif --error --all-targets

      - name: Upload SARIF
        # This step runs even if the previous one fails to aid in debugging
        if: always() 
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
