name: tfsec

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '39 0 * * 4'

jobs:
  tfsec:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Console output
      - name: tfsec console output
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          version: latest
          format: default
      
      # SARIF for GitHub Security
      - name: tfsec SARIF output
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          version: latest
          format: sarif
          additional_args: --out tfsec.sarif


      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec.sarif

