name: trivy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '40 5 * * 2'  # Every Tuesday at 05:40 UTC

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Build and Scan Docker Image
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: my-app  # Local image name
      DOCKERFILE_PATH: docker/Dockerfile  # <-- Change this if your Dockerfile is elsewhere
      BUILD_CONTEXT: docker  # <-- Folder containing your Dockerfile

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Build Docker image
      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build \
            -t $IMAGE_NAME:${{ github.sha }} \
            -f $DOCKERFILE_PATH \
            $BUILD_CONTEXT

      # 3️⃣ Run Trivy vulnerability scan
      - name: Run Trivy scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      # 4️⃣ Upload SARIF results to GitHub Security tab
      - name: Upload Trivy results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
