name: trivy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '40 5 * * 2'  # Every Tuesday at 05:40 UTC

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Build and Scan Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Find Dockerfile automatically
      - name: Find Dockerfile
        id: find_dockerfile
        run: |
          FILE=$(find . -type f -name 'Dockerfile' | head -n 1)
          if [ -z "$FILE" ]; then
            echo "No Dockerfile found!"
            exit 1
          fi
          DIR=$(dirname "$FILE")
          echo "dockerfile=$FILE" >> $GITHUB_OUTPUT
          echo "context=$DIR" >> $GITHUB_OUTPUT

           # 3️⃣ Build Docker image
      - name: Build Docker image
        run: |
          echo "Building Docker image from ${{ steps.find_dockerfile.outputs.dockerfile }} ..."
          docker build \
            -t my-app:${{ github.sha }} \
            -f "${{ steps.find_dockerfile.outputs.dockerfile }}" \
            "${{ steps.find_dockerfile.outputs.context }}"

      # 4️⃣ Run Trivy vulnerability scan (detailed output to console)
      - name: Run Trivy scanner (detailed)
        run: |
          trivy image --severity CRITICAL,HIGH,MEDIUM,LOW --format table --exit-code 1 --vuln-type os,library my-app:${{ github.sha }}

      # 5️⃣ Run Trivy vulnerability scan (SARIF for GitHub Security tab)
      - name: Run Trivy scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'my-app:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          exit-code: '1'
