name: Trivy PR Scan and Block

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Check if Dockerfile exists in repo root
      - name: Check for Dockerfile
        id: check_dockerfile
        run: |
          if [ -f ./Dockerfile ]; then
            echo "found=true" >> $GITHUB_ENV
          else
            echo "found=false" >> $GITHUB_ENV
          fi

      # 3️⃣ Build Docker image
      - name: Build Docker image
        if: env.found == 'true'
        run: |
          docker build -t my-app:${{ github.sha }} .

      # 4️⃣ Run Trivy scan on the image
      - name: Run Trivy vulnerability scanner
        if: env.found == 'true'
        uses: aquasecurity/trivy-action@v0.28.0
        id: trivy_scan
        with:
          image-ref: 'my-app:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          exit-code: '1'  # 🔴 Fail workflow if CRITICAL/HIGH vulns found

      # 5️⃣ Upload SARIF to Security tab
      - name: Upload Trivy SARIF results
        if: env.found == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      # 6️⃣ Post human-readable results as a PR comment
      - name: Post Trivy results as PR comment
        if: env.found == 'true'
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: trivy-results.sarif
          header: "🔒 Trivy Scan Results"
