name: Trivy Security Scan

on:
  pull_request:
    paths:
      - '**/Dockerfile'
      - '**/requirements.txt'
      - '**/Pipfile'
      - '**/pyproject.toml'
      - '**/*.py'

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.51.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.51.1_Linux-64bit.deb

      - name: Run Trivy file system scan
        run: |
          trivy fs . --format table --exit-code 1 --output trivy-report.txt || true

      - name: Post Trivy scan results as PR comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Trivy Security Scan Results**
            ```
            $(cat trivy-report.txt)
            ```
